### Register the user - OK
POST {{baseUrl}}/auths/login
Content-Type: application/json

{
  "username": "monad",
  "password": "monad"
}

### check his score when never played- OK
POST {{baseUrl}}/users/get
Content-Type: application/json
Authorization: {{userToken}}

### set his new score - OK
POST {{baseUrl}}/users/set
Content-Type: application/json
Authorization: {{userToken}}

{
  "score": 400
}

### check his score after played- OK
POST {{baseUrl}}/users/get
Content-Type: application/json
Authorization: {{userToken}}


### set his new score with score missing - KO
POST {{baseUrl}}/users/set
Content-Type: application/json
Authorization: {{userToken}}

### get the leaderboard - OK
GET {{baseUrl}}/users/scores
Content-Type: application/json


